name = "terio"
license = "GPL"
licenselink = "https://themeforest.net/licenses/terms/regular"
description = "Terio is a simple, minimal and responsive Creative Agency Portfolio Hugo Theme."
homepage = "https://bslthemes.com/"
tags = ["clean", "minimal", "blog", "responsive", "portfolio", "google analytics", "bootstrap", "portfolio", "digital", "agency", "it", "contact form", "creative"]
features = ['bootstrap 4', 'responsive design', 'blog', 'responsive', 'minimal', 'portfolio', 'portfolio single', 'hugo-theme', 'portfolio', 'creative', 'contact-form']
min_version = "0.41"

[author]
  name = "bslthemes Team"
  homepage = "https://bslthemes.com/"
